# Welcome to Sonic Pi v3.1
charizard = "C:/Users/miguel_gallardo/Documents/Audacity/Charizard.wav"
move1 = "C:/Users/miguel_gallardo/Downloads/move 1.wav"
move2 = "C:/Users/miguel_gallardo/Downloads/move 1.wav"
move3 = "C:/Users/miguel_gallardo/Downloads/move 3.wav"
move4 = "C:/Users/miguel_gallardo/Downloads/move 4.wav"
move5 = "C:/Users/miguel_gallardo/Downloads/move 5.wav"
move6 = "C:/Users/miguel_gallardo/Downloads/move 6.wav"
move7 = "C:/Users/miguel_gallardo/Downloads/move 7.wav"
move8 = "C:/Users/miguel_gallardo/Downloads/move 8.wav"
move9 = "C:/Users/miguel_gallardo/Downloads/move 9.wav"
use_bpm 194
with_fx :reverb do
  use_synth :chiplead
  sample charizard
  sleep 17.54
  play :D4
  play :A3
  play :D3
  sleep 2
  play :D4
  play :A3
  play :D3
  sleep 2
  play :D4
  play :A3
  play :D3
  sleep 2
  play :D4
  play :A3
  play :D3
  sleep 1
  play :D4
  play :B3
  play :D3
  play :E2
  sleep 1
  play :D4
  play :A3
  play :D3
  sleep 0.5
  play :D4
  play :D3
  sleep 1.5
  play :D4
  play :A3
  play :D3
  sleep 0.5
  play :D4
  play :A3
  play :D3
  sleep 1.5
  play :D4
  play :A3
  play :D3
  play :D2
  sleep 0.5
  play :D4
  play :A3
  play :D3
  sleep 1.5
  play :D4
  play :A3
  play :D3
  sleep 0.5
  play :D4
  play :A3
  play :D3
  sleep 0.5
  play :C3
  play :D4
  play :B3
  sleep 1
  play :D4
  play :A3
  play :D3
  sleep 0.5
  play :D4
  play :A3
  play :D3
  sleep 1.5
  play :D4
  play :A3
  play :D3
  sleep 0.5
  play :D4
  play :A3
  play :D3
  sleep 1.5
  play :D4
  play :A3
  play :D3
  sleep 0.5
  play :D4
  play :A3
  play :D3
  sleep 1.5
  play :D4
  play :A3
  play :D3
  sleep 0.5
  play :D4
  play :D3
  sleep 0.5
  play :D4
  play :B3
  sleep 1
  play :D4
  play :A3
  play :D3
  sleep 0.5
  play :D4
  play :D3
  sleep 1.5
  play :D4
  play :A3
  play :D3
  sleep 0.5
  play :D4
  play :A3
  play :D3
  sleep 1.5
  play :D3
  play :A3
  sleep 0.5
  play :D4
  play :A3
  play :D3
  sleep 1.5
  play :D4
  play :A3
  play :D3
  sleep 0.5
  play :D4
  play :A3
  play :D3
  sleep 0.5
  play :C5
  play :B3
  sleep 1
  live_loop :song do
    9.times do
      play :D4
      play :A3
      play :D3
      sleep 0.5
      play :D4
      play :A3
      sleep 0.5
      play :A4
      play :D4
      play :A3
      sleep 1
      play :D5
      play :A4
      play :D4
      play :A3
      play :D3
      sleep 0.5
      play :D5
      play :D4
      play :A3
      play :D3
      sleep 0.5
      play :B4
      play :D4
      play :B3
      sleep 1
      play :D4
      play :A3
      play :D3
      sleep 0.5
      play :D4
      play :D3
      sleep 0.5
      play :A4
      play :D4
      play :A3
      sleep 1
      play :D4
      play :A3
      play :D3
      sleep 0.5
      play :D4
      play :D3
      sleep 0.5
      play :B3
      play :D3
      sleep 1
      play :D4
      play :A3
      play :D3
      sleep 0.5
      play :D4
      play :A3
      play :D3
      sleep 0.5
      play :A4
      play :D4
      play :A3
      sleep 1
      play :D4
      play :A3
      play :D3
      sleep 0.5
      play :D4
      play :A3
      play :D3
      sleep 0.5
      play :B4
      play :B3
      sleep 1
      play :D4
      play :A3
      play :D3
      sleep 0.5
      play :D4
      play :A3
      play :D3
      sleep 0.5
      play :A4
      play :D4
      play :A3
      sleep 1
      play :D4
      play :A3
      play :D3
      sleep 0.5
      play :D4
      play :D3
      sleep 0.5
      play :F4
      play :D4
      play :G3
      sleep 1
      play :D4
      play :A3
      play :D3
      sleep 0.5
      play :D4
      play :A3
      play :D3
      sleep 0.5
      play :A4
      play :D4
      play :A3
      sleep 1
      play :D4
      play :A3
      play :D3
      sleep 0.5
      play :D4
      play :D3
      sleep 0.5
      play :B4
      play :D4
      play :B3
      sleep 1
      play :D4
      play :A3
      play :D3
      sleep 0.5
      play :D4
      play :A3
      play :D3
      sleep 0.5
      play :A4
      play :D4
      sleep 1
      play :D4
      play :A3
      play :D3
      sleep 0.5
      play :D4
      play :A3
      play :D3
      sleep 0.5
      play :B3
      play :D3
      sleep 1
    end
    stop
  end
  live_loop :attacks do
    9.times do
      sample choose ([move1, move2, move3, move4, move5, move6, move7, move8, move9])
      sleep 24
    end
  end
end


